### ISSUE TITLE
Is there a way to choose a random sound?

### ISSUE THREAD

**Issue by geoguide** [joshwcomeau/redux-sounds#11]
I want to do something like this:

`scan: { src: [ 'sound1.mp3', 'sound2.mp3', 'sound3.mp3' ] }`

but this will not work because it will always just succeed on sound1 and not ever choose the other two. Is there any way to get it to choose one at random? Other than exporting the array and manually choosing a random ~~action~~ string/key every time. Thanks.

**Comment by GeKorm** [comment]
Hi @geoguide I'm afraid this is something to be handled manually like the way you described. The src array is supposed to be the same sound in different formats, so that Howler.js (the underlying web audio library) can pick the first compatible one. 

[The src option](https://github.com/goldfire/howler.js/#src-arraystring--required) and the [Format Recommendations](https://github.com/goldfire/howler.js/#format-recommendations) from Howler.js
